services:
  hacktrack.testing.web:
    build:
      context: ..
      dockerfile: docker/prod/Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ../.env.production
    ports:
      - "3000:3000"
