# Use the environment variable directly from PowerShell
$USERPROFILE = $env:USERPROFILE

$SCRIPT_DIR = Split-Path -Parent $MyInvocation.MyCommand.Path
$FILE = Join-Path $SCRIPT_DIR "../config.json"
$CONFIG = Get-Content $FILE | ConvertFrom-Json

# project
$PROJECTS_PATH = "{0}\{1}" -f $USERPROFILE, $CONFIG.PROJECTS_PATH
$PROJECT_SOLUTION = $config.PROJECT_SOLUTION
$PROJECT_SOURCE = "{0}\{1}" -f $PROJECTS_PATH, $PROJECT_SOLUTION

# arhive
$ARCHIVE_NAME = "{0}{1}" -f $PROJECT_SOLUTION, ".tar.gz"

# server
$SERVER_TMP_PATH = $CONFIG.SERVER_TMP_PATH
$SERVER_PATH_PROJECT = "{0}/{1}" -f $SERVER_TMP_PATH, $PROJECT_SOLUTION

# docker
$DOCKER_NETWORK_NAME = $CONFIG.DOCKER_NETWORK_NAME
$DOCKER_FOLDER = $CONFIG.DOCKER_FOLDER
$DOCKER_COMPOSE_DEV_FILE = $CONFIG.DOCKER_COMPOSE_DEV_FILE
$DOCKER_COMPOSE_DEV_OVERRIDE_FILE = $CONFIG.DOCKER_COMPOSE_DEV_OVERRIDE_FILE
$DOCKER_COMPOSE_PROD_FILE = $CONFIG.DOCKER_COMPOSE_PROD_FILE

# ssh
$SSH_USER = $CONFIG.SSH_USER
$SSH_SERVER = $CONFIG.SSH_SERVER
$SSH_PORT = $CONFIG.SSH_PORT