# PROJECTS
PROJECTS_PATH="$HOME/WebstormProjects"

# PROJECT
PROJECT_SOLUTION="DKH.Commerce.Web.Admin"
PROJECT_SOURCE="$PROJECTS_PATH/$PROJECT_SOLUTION"

# ARCHIVE
ARCHIVE_NAME="$PROJECT_SOLUTION.tar.gz"

# SERVER
SERVER_TMP_PATH="/tmp"
SERVER_PATH_PROJECT="$SERVER_TMP_PATH/$PROJECT_SOLUTION"

# DOCKER
DOCKER_NETWORK_NAME="dkh"
DOCKER_FOLDER="docker"
DOCKER_COMPOSE_DEV_FILE="docker-compose.dev.yml"
DOCKER_COMPOSE_DEV_OVERRIDE_FILE="docker-compose.dev.override.yml"
DOCKER_COMPOSE_PROD_FILE="docker-compose.prod.yml"

# SSH
SSH_USER="root"
SSH_SERVER="82.97.249.148"
SSH_PORT="22"
